#!/bin/bash

function deactivate_conda_if_in_env() {
  if [ "$CONDA_SHLVL" -eq "1" ]; then
      conda deactivate
  fi
}

# On Berzelius
CONDA_ENV="fastssl"

# shellcheck source=/dev/null
eval "$(/proj/memorization/users/x_matga/miniconda3/bin/conda shell.bash hook)"

echo "Setting env on ${SLURMD_NODENAME}"
nvidia-smi
conda activate $CONDA_ENV
user="$USER"
if [ -z "$user" ]; then
    user="$SLURM_JOB_USER"
fi
echo "SETUP_ENV - user=$user"
SAVE_DIR="/proj/memorization/smoothness/checkpoints"
OUTPUT="$SAVE_DIR"
DATA_DIR="/proj/memorization/data"
DEVICE="cuda"

# set up wandb
WANDB_API_KEY="a31e51e69e539eaffb5d3683c402e59375cd47e6"
WANDB_CACHE_DIR="/scratch/local"


# Set this to zero, disabling random salts for hashes
# if an arg is given, then use that instead
PYTHONHASHSEED=0
for (( i=1; i< "$#"; i++ )); do
    if [ "${!i}" = "--s_python-hash-seed" ]; then
        validx=$((i+1))
        PYTHONHASHSEED=${!validx}
    fi
done

echo "SETUP_ENV - PYTHONHASHSEED=$PYTHONHASHSEED"


export SAVE_DIR DATA_DIR WORKERS DEVICE PYTHONHASHSEED OUTPUT WANDB_API_KEY WANDB_CACHE_DIR

echo "SETUP_ENV - Current ENV is:"
printenv
